export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'

export const SIGNUP_USER_REQUEST = 'SIGNUP_USER_REQUEST'
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE'
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS'

export const LOGOUT_USER = 'LOGOUT_USER'

export const GET_USER_INFO_REQUEST = 'GET_USER_INFO_REQUEST'
export const GET_USER_INFO_FAILURE = 'GET_USER_INFO_FAILURE'
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'

export const GET_TRANSACTIONS_REQUEST = 'GET_TRANSACTIONS_REQUEST'
export const GET_TRANSACTIONS_FAILURE = 'GET_TRANSACTIONS_FAILURE'
export const GET_TRANSACTIONS_SUCCESS = 'GET_TRANSACTIONS_SUCCESS'
export const SORT_TRANSACTIONS = 'SORT_TRANSACTIONS'

export const GET_SUGGESTIONS_REQUEST = 'GET_SUGGESTIONS_REQUEST'
export const GET_SUGGESTIONS_FAILURE = 'GET_SUGGESTIONS_FAILURE'
export const GET_SUGGESTIONS_SUCCESS = 'GET_SUGGESTIONS_SUCCESS'
export const CLEAR_SUGGESTIONS = 'CLEAR_SUGGESTIONS'
export const SET_AUTOCOMPLETE_VALUE = 'SET_AUTOCOMPLETE_VALUE'

export const CREATE_TRANSACTION_SET_USERNAME = 'CREATE_TRANSACTION_SET_USERNAME'
export const CREATE_TRANSACTION_SET_AMOUNT = 'CREATE_TRANSACTION_SET_AMOUNT'
export const CREATE_TRANSACTION_REQUEST = 'CREATE_TRANSACTION_REQUEST'
export const CREATE_TRANSACTION_FAILURE = 'CREATE_TRANSACTION_FAILURE'
export const CREATE_TRANSACTION_SUCCESS = 'CREATE_TRANSACTION_SUCCESS'
export const RESET_TRANSACTION = 'RESET_TRANSACTION'